### ISSUE TITLE
Strict the stylelint rules or remove?

### ISSUE THREAD

**Issue by monochrome-yeh** [juwai/juwai-lint-cfg#18] opened 2016-10-09 06:20 UTC
Hello @juwai/frontend , We always encounter warning notification about stylelint,

Some rules are as below:

``` son
        "font-family-name-quotes": [ "always-where-recommended", {
            "severity": "warning"
        }],

        "font-weight-notation": [ "numeric", {
            "severity": "warning"
        }],

        "unit-blacklist": [ ["cm", "mm", "q", "in", "pt", "pc"], {
            "severity": "warning"
        }],

        "declaration-no-important": [ true, {
            "severity": "warning"
        }],

        "selector-no-id": [ true, {
            "severity": "warning"
        }],

        "selector-no-type": [ true, {
            "severity": "warning"
        }],

        "no-duplicate-selectors": [ true, {
            "severity": "warning"
        }],

        "no-indistinguishable-colors": [ true, {
            "severity": "warning"
        }],
```

There're too many informations would disturb us
Do we really need them or we could set `severity` to `error`(strict) and then replace the problems?

**Comment by stuartwan** [comment] 2016-10-14 08:39
@arkhi @HouCoder what's your input on this?

**Comment by HouCoder** [comment] 2016-10-19 03:28
**No one cares about warning, unless they encountered an error.**

I just glanced all the stylelint errors in latest master branch in our most important project. I can sort them in to those types:

### 1: Expected "#ff0000" to be "#f00" (color-hex-length)

Reasonable, we should fix this and make a rule more strict, convert it to error.

### 2: Unexpected named color "white" (color-named)

Reasonable, we should fix this and make a rule more strict, convert it to error.

### 3: Unexpected unit (length-zero-no-unit)

Reasonable, we should fix this and make a rule more strict, convert it to error.

### 4: Expected double quotes (string-quotes)

Most of them were caused by [postcss-assets](https://github.com/assetsjs/postcss-assets) plugin, I checked their documentation, seems they didn't provide a way to specify single quote or double quote. I think we can leave it for now.

### 5: Unexpected !important (declaration-no-important)

Not reasonable, we use `!important` in every single responsibility classes, e.g. `is-hidden`, `is-active`, I know sometimes people(also include me) abuse `!important`, but they will be noticed during the code review process.

### 6: Unexpected type selector (selector-no-type)

[selector-no-type](https://github.com/stylelint/stylelint/tree/master/src/rules/selector-no-type), I tried my best to give every HTML DOM a proper class name as possible as I can, but for me sometimes it's very hard to work out a proper name, we can keep it, but reasonable class names take more time.

### 7: Unexpected indistinguishable colors "#ddd" and "#dcdcdc" (no-indistinguishable-colors)

My biggest concern about our color settings is we migrated legacy color to a brand new project, we have new standards, and we should drop legacy colors in our new project, if we could remove all the legacy colors I'm OK with removing this rule.

**Comment by vijayk1989** [comment] 2016-10-21 07:54
I personally don't pay that much attention to the warnings (I know it's bad) so I am in favor of changing it to errors instead. However I have not worked much with juwai.com front-end so I think @HouCoder's suggestions are more important for the warnings listed. I personally think a lot of developers abuse `!important` but for legacy systems we don't have much choice but to use it. So for new systems I think we can set `!important` warning to an error but keep it as a warning for previous systems.

**Comment by HouCoder** [comment] 2016-10-25 09:05
Fellows, does my proposal was made sense to you, if it doesn't please speak up. I'll close this PR and create a new ticket for applying my proposal in this Friday.

**Comment by stuartwan** [comment] 2016-10-28 08:31
Closed during Retro meeting.

**Closed as completed** 2016-10-28 08:30 UTC

**Comment by HouCoder** [comment] 2016-10-31 10:51
Issue created: CON-554
